# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a031bb604d93df867006d404f4026a5a997cdf13cf2affa4b5c21102cfc131aaeaf68fcec16f53903b63e9c39257afef31bb146b1ae8cb6bfa85ef542aae58ed

test:
  secret_key_base: 19385602d65d8d436d98f03f087f70d0db1dbb166e25a6564a1b95a14d7c3dd921da34caef2380735ecc41687a555c5c5ad0419620b6b470fc9ffce42d7c25d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
